server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mariadb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ms159753

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    token:
      security-key: secret-key
      expiration-length: 3600000

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token